//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intellij_Assessment
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Assessment
    {
        public int fdId { get; set; }
        [Display(Name ="Name")]
        [Required(ErrorMessage ="Cannot Insert Null value for Name in database.")]
        public string fdName { get; set; }
        [Display(Name ="Description")]
        public string fdDescription { get; set; }
        [Display(Name = "Date Created")]
        public DateTime? fdDateCreated {
            get;set;
        }
        [Display(Name = "Date Modified")]
        public DateTime fdDateModified {
            get { return dateNow; }
            set { dateNow = value; }
        }

        private DateTime dateNow = DateTime.Now;

    }
}
